services:
  nure-timetable-api-docs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
  
  nure-timetable-api-docs-uk:
    build:
      dockerfile: uk.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
